import { scoreOpportunity } from "./scoring";
import type { Opportunity, RawOpportunity, SortKey } from "./types";

const RAW: RawOpportunity[] = [
  {
    id: "asics-kayano-14-wide-hk",
    query: "asics gel kayano 14 wide",
    queryZh: "Asics Gel-Kayano 14 廣楦 香港",
    brand: "Asics",
    model: "Gel-Kayano 14",
    category: "lifestyle",
    region: "HK",
    intent: "size",
    playType: "product-gap",
    monthlyVolume: 2400,
    volumeTrendPct: 38,
    trendSeries: [22, 24, 21, 28, 31, 36, 40, 48, 55, 62, 70, 81],
    keywordDifficulty: 18,
    serpSaturation: 24,
    topResults: [
      { title: "GEL-KAYANO 14", domain: "asics.com", type: "brand" },
      { title: "Kayano 14 上腳", domain: "youtube.com", type: "ugc" },
      { title: "StockX listings", domain: "stockx.com", type: "marketplace" },
    ],
    relatedQueries: [
      "kayano 14 2e",
      "kayano 14 腳寬",
      "kayano 14 vs 1130",
      "asics 廣楦 香港",
    ],
    chatgptMentioned: false,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 1,
    aiShareOfVoice: 8,
    unansweredAngle: "AI 答案只講標準 D 楦，幾乎無覆蓋 2E/寬腳喺香港邊度有現貨。",
    cities: [
      { city: "旺角", demand: 82, supply: 28 },
      { city: "銅鑼灣", demand: 70, supply: 34 },
      { city: "沙田", demand: 61, supply: 18 },
      { city: "觀塘", demand: 54, supply: 16 },
    ],
    play: {
      title: "專做廣楦 Kayano 代購 + 現貨清單",
      whyHidden: "搜尋升得好快，但 SERP 幾乎全係品牌頁同英文 unpacking，冇人系統整理香港寬腳現貨。",
      suggestedMove:
        "每週更新「香港有貨／要等」表，鎖定 2E 同女裝寬楦。內容用 FAQ 結構寫，方便 GEO 被 AI 引用。",
      effort: "medium",
      timeToSignal: "3–6 週",
    },
  },
  {
    id: "salomon-xt6-vs-xt4",
    query: "salomon xt-6 vs xt-4",
    queryZh: "Salomon XT-6 同 XT-4 分別",
    brand: "Salomon",
    model: "XT-6 / XT-4",
    category: "trail",
    region: "HK",
    intent: "compare",
    playType: "content",
    monthlyVolume: 1900,
    volumeTrendPct: 22,
    trendSeries: [40, 38, 41, 44, 47, 49, 52, 55, 58, 61, 66, 72],
    keywordDifficulty: 21,
    serpSaturation: 31,
    topResults: [
      { title: "XT-6 product", domain: "salomon.com", type: "brand" },
      { title: "XT-6 review", domain: "reddit.com", type: "forum" },
      { title: "Goat listings", domain: "goat.com", type: "marketplace" },
    ],
    relatedQueries: [
      "xt-6 著山?",
      "xt-4 街著",
      "salomon 行山 香港",
      "xt-6 尺碼偏細",
    ],
    chatgptMentioned: true,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 2,
    aiShareOfVoice: 16,
    unansweredAngle: "英文比較文主導；中文搜尋者想知街著 vs 行山、香港濕地適用度，AI 幾乎引用唔到本地來源。",
    cities: [
      { city: "中環", demand: 64, supply: 40 },
      { city: "旺角", demand: 78, supply: 30 },
      { city: "荃灣", demand: 58, supply: 22 },
    ],
    play: {
      title: "中文對照評測：街著、行山、濕地",
      whyHidden: "需求穩定上升，但頁面全係品牌同海外論壇，中文意圖冇被承接。",
      suggestedMove:
        "做一頁可被引用嘅對照表（重量、防滑、尺碼、香港天氣），再剪成短片。呢個係典型 SEO 內容缺口 + GEO 引用缺口。",
      effort: "low",
      timeToSignal: "2–4 週",
    },
  },
  {
    id: "nb-1906r-restock-hk",
    query: "new balance 1906r restock hong kong",
    queryZh: "NB 1906R 香港補貨",
    brand: "New Balance",
    model: "1906R",
    category: "lifestyle",
    region: "HK",
    intent: "restock",
    playType: "resale",
    monthlyVolume: 3200,
    volumeTrendPct: 44,
    trendSeries: [18, 20, 24, 30, 28, 36, 42, 51, 60, 68, 77, 90],
    keywordDifficulty: 27,
    serpSaturation: 38,
    topResults: [
      { title: "1906R", domain: "newbalance.com.hk", type: "brand" },
      { title: "1906R 發售", domain: "hypebeast.com", type: "media" },
      { title: "Carousell 1906R", domain: "carousell.com.hk", type: "marketplace" },
    ],
    relatedQueries: [
      "1906r protection pack 香港",
      "1906r 抽籤",
      "1906r 細碼",
      "1906r 灰 補貨",
    ],
    chatgptMentioned: false,
    perplexityCited: false,
    aiOverviewPresent: true,
    citationCount: 3,
    aiShareOfVoice: 19,
    unansweredAngle: "AI Overview 只指向品牌官網；無人提供可行動嘅香港補貨時間表同尺碼缺口。",
    cities: [
      { city: "銅鑼灣", demand: 88, supply: 45 },
      { city: "旺角", demand: 91, supply: 52 },
      { city: "尖沙咀", demand: 74, supply: 41 },
    ],
    play: {
      title: "補貨雷達 + 細碼／女碼套利",
      whyHidden: "搜尋量高但競爭仍係媒體發售稿，唔係即時存貨情報。",
      suggestedMove:
        "用公開發售日曆 + 門市觀察，專做 US 6–7.5 同女裝。Telegram 通知比內容站更快驗證付費意願。",
      effort: "medium",
      timeToSignal: "1–3 週",
    },
  },
  {
    id: "hoka-clifton-9-vs-10-hk",
    query: "hoka clifton 9 vs 10",
    queryZh: "Hoka Clifton 9 同 10 香港",
    brand: "Hoka",
    model: "Clifton 9 / 10",
    category: "running",
    region: "HK",
    intent: "compare",
    playType: "ai-visibility",
    monthlyVolume: 4100,
    volumeTrendPct: 17,
    trendSeries: [50, 52, 51, 55, 58, 60, 63, 64, 68, 70, 73, 76],
    keywordDifficulty: 34,
    serpSaturation: 48,
    topResults: [
      { title: "Clifton 10", domain: "hoka.com", type: "brand" },
      { title: "Clifton 10 review", domain: "runnersworld.com", type: "media" },
      { title: "Clifton 9 leftover", domain: "runningwarehouse.com", type: "shop" },
    ],
    relatedQueries: [
      "clifton 10 香港價錢",
      "clifton 9 清貨",
      "hoka  pronation 香港",
      "clifton vs bondi",
    ],
    chatgptMentioned: true,
    perplexityCited: true,
    aiOverviewPresent: true,
    citationCount: 11,
    aiShareOfVoice: 42,
    unansweredAngle: "海外評測已被 AI 大量引用；香港價錢、清貨、門市試腳同潮濕天氣幾乎空白。",
    cities: [
      { city: "銅鑼灣", demand: 72, supply: 58 },
      { city: "沙田", demand: 66, supply: 30 },
      { city: "屯門", demand: 49, supply: 14 },
    ],
    play: {
      title: "本地化 Clifton 決策頁（價錢 + 試腳店）",
      whyHidden: "全球 SEO 已捲，但 GEO 引用源全係英文跑誌。香港意圖仍然無權威頁。",
      suggestedMove:
        "做『邊個應該買 9 清貨、邊個應該上 10』，附香港門市同現價。目標係成為 AI 會引用嘅本地來源，而唔係再寫一篇全球評測。",
      effort: "medium",
      timeToSignal: "4–8 週",
    },
  },
  {
    id: "nike-vomero-5-alt-hk",
    query: "nike vomero 5 alternative",
    queryZh: "Nike Vomero 5 平價替代",
    brand: "Nike",
    model: "Vomero 5",
    category: "lifestyle",
    region: "HK",
    intent: "compare",
    playType: "content",
    monthlyVolume: 2800,
    volumeTrendPct: 29,
    trendSeries: [30, 32, 35, 38, 41, 48, 52, 55, 61, 67, 74, 80],
    keywordDifficulty: 23,
    serpSaturation: 29,
    topResults: [
      { title: "Vomero 5", domain: "nike.com", type: "brand" },
      { title: "Vomero 5 lookalikes", domain: "reddit.com", type: "forum" },
      { title: "Vomero 5 穿搭", domain: "xiaohongshu.com", type: "ugc" },
    ],
    relatedQueries: [
      "vomero 5 vs 1906r",
      "vomero 5 假貨",
      "vomero 5 細碼",
      "vomero 5 平替 香港",
    ],
    chatgptMentioned: false,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 0,
    aiShareOfVoice: 6,
    unansweredAngle: "人問平替，AI 幾乎答唔到香港買得到、真假風險同尺碼對照。",
    cities: [
      { city: "旺角", demand: 86, supply: 33 },
      { city: "觀塘", demand: 60, supply: 21 },
      { city: "元朗", demand: 47, supply: 12 },
    ],
    play: {
      title: "Vomero 5 平替矩陣（NB / Asics / 二手）",
      whyHidden: "需求升、難度低、GEO 幾乎零覆蓋，係 MVP 最典型嘅隱市機會。",
      suggestedMove:
        "用對照表答『外型接近、腳感接近、預算接近』三條路徑，連去可信二手同正貨店，避免導去無保證貨源。",
      effort: "low",
      timeToSignal: "2–5 週",
    },
  },
  {
    id: "on-cloudmonster-2-where-hk",
    query: "on cloudmonster 2 where to buy hong kong",
    queryZh: "On Cloudmonster 2 香港邊度買",
    brand: "On",
    model: "Cloudmonster 2",
    category: "running",
    region: "HK",
    intent: "buy",
    playType: "local-retail",
    monthlyVolume: 1300,
    volumeTrendPct: 14,
    trendSeries: [36, 38, 40, 39, 42, 44, 46, 48, 50, 53, 55, 58],
    keywordDifficulty: 16,
    serpSaturation: 22,
    topResults: [
      { title: "On official", domain: "on.com", type: "brand" },
      { title: "Cloudmonster 2", domain: "i.run", type: "shop" },
      { title: "On HK store", domain: "timeout.com", type: "media" },
    ],
    relatedQueries: [
      "on running 門市 香港",
      "cloudmonster 2 尺碼",
      "on 波鞋 折扣 香港",
    ],
    chatgptMentioned: false,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 1,
    aiShareOfVoice: 9,
    unansweredAngle: "購買意圖好明確，但搜尋結果同 AI 都唔會列出現貨門市同碼數。",
    cities: [
      { city: "中環", demand: 71, supply: 48 },
      { city: "太古", demand: 55, supply: 20 },
      { city: "沙田", demand: 49, supply: 15 },
    ],
    play: {
      title: "門市現貨地圖（SKU 級）",
      whyHidden: "量唔算爆，但意圖係交易，轉換率高過資訊詞。",
      suggestedMove:
        "每週打六間跑店，公開 Cloudmonster 2 現碼。之後可擴到其他 On 型號，做成香港跑鞋庫存層。",
      effort: "medium",
      timeToSignal: "2–4 週",
    },
  },
  {
    id: "sneaker-cleaning-tst",
    query: "sneaker cleaning tsim sha tsui",
    queryZh: "波鞋清洗 尖沙咀",
    brand: "Service",
    model: "清洗護理",
    category: "service",
    region: "HK",
    intent: "service",
    playType: "service",
    monthlyVolume: 1600,
    volumeTrendPct: 11,
    trendSeries: [44, 45, 46, 47, 48, 50, 51, 52, 54, 55, 57, 59],
    keywordDifficulty: 12,
    serpSaturation: 19,
    topResults: [
      { title: "洗鞋店清單", domain: "openrice.com", type: "media" },
      { title: "洗波鞋價錢", domain: "facebook.com", type: "ugc" },
      { title: "DIY 洗鞋", domain: "youtube.com", type: "ugc" },
    ],
    relatedQueries: [
      "洗 AJ 尖沙咀",
      "波鞋護理 九龍",
      "suade 清洗 香港",
      "洗鞋 即日",
    ],
    chatgptMentioned: false,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 0,
    aiShareOfVoice: 4,
    unansweredAngle: "本地服務詞幾乎冇結構化頁；AI 無法推薦可信店同周轉時間。",
    cities: [
      { city: "尖沙咀", demand: 80, supply: 26 },
      { city: "旺角", demand: 84, supply: 47 },
      { city: "觀塘", demand: 51, supply: 18 },
    ],
    play: {
      title: "即日洗鞋 + 鑑定增值",
      whyHidden: "SEO 難度極低，競爭係 Facebook 帖而唔係專業頁。",
      suggestedMove:
        "落地頁寫清物料、周轉、保險同前後對比。同步做 GEO：讓 ChatGPT 搜『尖沙咀洗 AJ』時有可引用來源。",
      effort: "high",
      timeToSignal: "4–10 週",
    },
  },
  {
    id: "waterproof-trail-hk-rain",
    query: "waterproof trail shoes hong kong rainy season",
    queryZh: "防水行山鞋 香港梅雨",
    brand: "Category",
    model: "防水行山鞋",
    category: "trail",
    region: "HK",
    intent: "buy",
    playType: "content",
    monthlyVolume: 2100,
    volumeTrendPct: 33,
    trendSeries: [20, 18, 19, 24, 36, 48, 62, 70, 66, 58, 54, 72],
    keywordDifficulty: 19,
    serpSaturation: 27,
    topResults: [
      { title: "Best trail shoes", domain: "outsideonline.com", type: "media" },
      { title: "Gore-Tex hiking", domain: "decathlon.hk", type: "shop" },
      { title: "行山鞋推薦", domain: "discuss.com.hk", type: "forum" },
    ],
    relatedQueries: [
      "salomon gore-tex 香港",
      "行山波 唔跣",
      "梅雨 行山鞋",
      "hoka speedgoat 防水",
    ],
    chatgptMentioned: true,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 2,
    aiShareOfVoice: 14,
    unansweredAngle: "海外『最佳行山鞋』清單忽略香港濕熱：Gore-Tex 焗腳同岩石跣情況。",
    cities: [
      { city: "荃灣", demand: 73, supply: 29 },
      { city: "大埔", demand: 68, supply: 21 },
      { city: "西貢", demand: 77, supply: 18 },
    ],
    play: {
      title: "梅雨季節選鞋指南（本地地形）",
      whyHidden: "有季節性高峰，內容卻全年用北美清單充數。",
      suggestedMove:
        "按麥理浩、西貢、大帽山分場景推薦。季節前 6 週發布，之後用 affiliate / 本地店分帳。",
      effort: "low",
      timeToSignal: "季節前 4 週",
    },
  },
  {
    id: "wide-toe-box-hk",
    query: "wide toe box sneakers hong kong",
    queryZh: "寬頭波鞋 香港",
    brand: "Category",
    model: "Wide toe box",
    category: "lifestyle",
    region: "HK",
    intent: "size",
    playType: "product-gap",
    monthlyVolume: 1500,
    volumeTrendPct: 41,
    trendSeries: [16, 18, 20, 22, 26, 30, 36, 42, 50, 58, 66, 78],
    keywordDifficulty: 14,
    serpSaturation: 18,
    topResults: [
      { title: "Altra running", domain: "altrarunning.com", type: "brand" },
      { title: "Wide sneakers", domain: "reddit.com", type: "forum" },
      { title: "New Balance 2E", domain: "newbalance.com", type: "brand" },
    ],
    relatedQueries: [
      "脚闊 波鞋 女",
      "altra 香港",
      "topo athletic 香港",
      "new balance 4e",
    ],
    chatgptMentioned: false,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 1,
    aiShareOfVoice: 7,
    unansweredAngle: "健康／足科意圖上升，但香港零售同內容都仲用標準楦主導。",
    cities: [
      { city: "九龍塘", demand: 57, supply: 14 },
      { city: "沙田", demand: 63, supply: 19 },
      { city: "銅鑼灣", demand: 60, supply: 28 },
    ],
    play: {
      title: "寬頭選品店（Altra / Topo / NB 2E）",
      whyHidden: "搜尋曲線陡，供應幾乎只有標準時尚款。",
      suggestedMove:
        "先用內容站驗證需求，再做小庫存。GEO 上要回答『扁平足、拇指外翻、長跑』三個臨床場景。",
      effort: "high",
      timeToSignal: "6–12 週",
    },
  },
  {
    id: "mizuno-wave-rider-hk-marathon",
    query: "mizuno wave rider hong kong marathon",
    queryZh: "Mizuno Wave Rider 香港馬拉松",
    brand: "Mizuno",
    model: "Wave Rider",
    category: "running",
    region: "HK",
    intent: "buy",
    playType: "local-retail",
    monthlyVolume: 980,
    volumeTrendPct: 26,
    trendSeries: [24, 22, 21, 25, 28, 33, 40, 48, 52, 49, 46, 58],
    keywordDifficulty: 11,
    serpSaturation: 16,
    topResults: [
      { title: "Wave Rider", domain: "mizuno.com", type: "brand" },
      { title: "HK Marathon expo", domain: "hkmarathon.com", type: "media" },
      { title: "Rider review", domain: "believeintherun.com", type: "media" },
    ],
    relatedQueries: [
      "mizuno 香港 門市",
      "wave rider 31 折扣",
      "馬拉松 訓練鞋 香港",
    ],
    chatgptMentioned: false,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 0,
    aiShareOfVoice: 5,
    unansweredAngle: "賽事週期搜尋上升，AI 同 Google 都冇本地訓練鞋購買路徑。",
    cities: [
      { city: "維園", demand: 69, supply: 22 },
      { city: "沙田", demand: 64, supply: 25 },
      { city: "北角", demand: 48, supply: 17 },
    ],
    play: {
      title: "馬拉松訓練週選鞋日曆",
      whyHidden: "量細但季節轉換高，品牌頁 capturen 唔到『而家該買邊一雙』。",
      suggestedMove:
        "對準 10–12 月訓練期，做配速分層推薦 + 門市試跑。適合同獨立跑店分成。",
      effort: "low",
      timeToSignal: "賽事季前",
    },
  },
  {
    id: "jordan-4-military-blue-lc",
    query: "jordan 4 military blue legit check",
    queryZh: "Jordan 4 Military Blue 真假",
    brand: "Jordan",
    model: "AJ4 Military Blue",
    category: "basketball",
    region: "HK",
    intent: "resale",
    playType: "service",
    monthlyVolume: 5400,
    volumeTrendPct: 9,
    trendSeries: [70, 68, 72, 74, 71, 73, 75, 76, 78, 80, 79, 83],
    keywordDifficulty: 46,
    serpSaturation: 62,
    topResults: [
      { title: "LC guide", domain: "reddit.com", type: "forum" },
      { title: "StockX", domain: "stockx.com", type: "marketplace" },
      { title: "YouTube LC", domain: "youtube.com", type: "ugc" },
    ],
    relatedQueries: [
      "aj4 真假 香港",
      "military blue 2024",
      "鑑定 波鞋 收費",
      "carousell jordan 真假",
    ],
    chatgptMentioned: true,
    perplexityCited: true,
    aiOverviewPresent: true,
    citationCount: 18,
    aiShareOfVoice: 51,
    unansweredAngle: "全球 LC 內容已飽和；香港 Carousell／門市即場鑑定仍然分散。",
    cities: [
      { city: "旺角", demand: 93, supply: 61 },
      { city: "深水埗", demand: 77, supply: 44 },
      { city: "屯門", demand: 50, supply: 12 },
    ],
    play: {
      title: "本地即場鑑定（Carousell 成交配套）",
      whyHidden: "SEO 分數唔突出，但服務意圖喺香港仲可以變現。唔好再做一篇全球 LC 文。",
      suggestedMove:
        "旺角設預約鑑定，出短片只講本地常見假貨批次。收費鑑定 + 寄賣抽成。",
      effort: "high",
      timeToSignal: "3–6 週",
    },
  },
  {
    id: "saucony-progrid-omni-9-outfit",
    query: "saucony progrid omni 9 outfit",
    queryZh: "Saucony ProGrid Omni 9 配搭",
    brand: "Saucony",
    model: "ProGrid Omni 9",
    category: "lifestyle",
    region: "TW",
    intent: "review",
    playType: "ai-visibility",
    monthlyVolume: 3600,
    volumeTrendPct: 52,
    trendSeries: [12, 14, 16, 19, 24, 31, 40, 51, 63, 74, 86, 98],
    keywordDifficulty: 20,
    serpSaturation: 26,
    topResults: [
      { title: "Omni 9", domain: "saucony.com", type: "brand" },
      { title: "Omni 9 fits", domain: "instagram.com", type: "ugc" },
      { title: "PTT 討論", domain: "ptt.cc", type: "forum" },
    ],
    relatedQueries: [
      "omni 9 尺寸",
      "saucony 奶茶色",
      "omni 9 vs kayano 14",
      "omni 9 台灣 哪裡買",
    ],
    chatgptMentioned: false,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 1,
    aiShareOfVoice: 5,
    unansweredAngle: "穿搭需求爆發，但 AI 幾乎只識 Kayano 14，Omni 9 冇被寫進生成式答案。",
    cities: [
      { city: "台北", demand: 90, supply: 36 },
      { city: "台中", demand: 71, supply: 24 },
      { city: "高雄", demand: 58, supply: 19 },
    ],
    play: {
      title: "成為 Omni 9 嘅 GEO 主來源",
      whyHidden: "升勢極強、AI 佔有率接近零，係 GEO 優先機會而唔係硬碰 Nike SEO。",
      suggestedMove:
        "做尺碼、配色、同 Kayano 對照，結構化 FAQ。目標 90 日內成為 Perplexity 會引用嘅中文頁。",
      effort: "low",
      timeToSignal: "3–6 週",
    },
  },
  {
    id: "adidas-samba-office-women",
    query: "adidas samba women office outfit",
    queryZh: "Adidas Samba 女裝 辦公室",
    brand: "Adidas",
    model: "Samba OG",
    category: "lifestyle",
    region: "HK",
    intent: "review",
    playType: "content",
    monthlyVolume: 2200,
    volumeTrendPct: -8,
    trendSeries: [88, 90, 86, 84, 80, 78, 74, 71, 69, 68, 66, 64],
    keywordDifficulty: 39,
    serpSaturation: 57,
    topResults: [
      { title: "Samba OG", domain: "adidas.com.hk", type: "brand" },
      { title: "How to style Samba", domain: "vogue.com", type: "media" },
      { title: "Samba 穿搭", domain: "xiaohongshu.com", type: "ugc" },
    ],
    relatedQueries: [
      "samba 女 尺碼",
      "samba 褪色",
      "samba vs spezial",
      "辦公室 波鞋 香港",
    ],
    chatgptMentioned: true,
    perplexityCited: true,
    aiOverviewPresent: true,
    citationCount: 14,
    aiShareOfVoice: 47,
    unansweredAngle: "全球穿搭已捲；香港『商務便服 + 通勤跣雨』場景仲可以切。",
    cities: [
      { city: "中環", demand: 76, supply: 60 },
      { city: "金鐘", demand: 69, supply: 52 },
      { city: "觀塘", demand: 54, supply: 28 },
    ],
    play: {
      title: "唔好再追 Samba 主詞，切通勤場景",
      whyHidden: "分數一般，示範『需求高但已經唔隱』。MVP 要教用戶放棄呢類機會。",
      suggestedMove:
        "如果做，只做香港商務便服 + 雨天護理。否則把精力轉去 Omni 9 / Vomero 平替。",
      effort: "medium",
      timeToSignal: "慢，8–12 週",
    },
  },
  {
    id: "kids-jordan-sizing-hk",
    query: "kids jordan sizing hong kong",
    queryZh: "兒童 Jordan 香港 尺碼",
    brand: "Jordan",
    model: "Kids Jordan",
    category: "basketball",
    region: "HK",
    intent: "size",
    playType: "product-gap",
    monthlyVolume: 1100,
    volumeTrendPct: 19,
    trendSeries: [32, 33, 34, 36, 38, 40, 42, 45, 47, 50, 52, 55],
    keywordDifficulty: 15,
    serpSaturation: 21,
    topResults: [
      { title: "Jordan kids", domain: "nike.com", type: "brand" },
      { title: "Kids sizing", domain: "footlocker.com", type: "shop" },
      { title: "親子波鞋", domain: "baby-kingdom.com", type: "forum" },
    ],
    relatedQueries: [
      "童裝 aj 香港",
      "ps vs td 尺碼",
      "兒童波鞋 腳闊",
    ],
    chatgptMentioned: false,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 0,
    aiShareOfVoice: 3,
    unansweredAngle: "家長搜尺碼同真假，但結果全係美國童裝表，冇香港門市碼數。",
    cities: [
      { city: "沙田", demand: 70, supply: 24 },
      { city: "將軍澳", demand: 66, supply: 18 },
      { city: "馬鞍山", demand: 52, supply: 11 },
    ],
    play: {
      title: "童裝 AJ 尺碼轉換 + 可靠貨源",
      whyHidden: "低競爭、家庭客單價高、可重複購買。",
      suggestedMove:
        "做 PS/TD/GS 對照同實腳照片。搭配鑑定，解決家長最大恐懼。",
      effort: "medium",
      timeToSignal: "3–6 週",
    },
  },
  {
    id: "trail-shoes-sai-kung",
    query: "trail running shoes sai kung",
    queryZh: "越野跑鞋 西貢",
    brand: "Category",
    model: "越野跑鞋",
    category: "trail",
    region: "HK",
    intent: "buy",
    playType: "local-retail",
    monthlyVolume: 720,
    volumeTrendPct: 21,
    trendSeries: [28, 29, 30, 31, 33, 35, 38, 41, 44, 46, 48, 52],
    keywordDifficulty: 9,
    serpSaturation: 14,
    topResults: [
      { title: "Best trail 2026", domain: "runrepeat.com", type: "media" },
      { title: "西貢行山", domain: "discoverhongkong.com", type: "media" },
      { title: "Speedgoat", domain: "hoka.com", type: "brand" },
    ],
    relatedQueries: [
      "西貢 岩石 跑鞋",
      "speedgoat vs peregrine",
      "越野跑 租鞋 香港",
    ],
    chatgptMentioned: false,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 0,
    aiShareOfVoice: 2,
    unansweredAngle: "地點意圖好強，清單文卻講全球『最佳越野鞋』。",
    cities: [
      { city: "西貢", demand: 81, supply: 12 },
      { city: "坑口", demand: 54, supply: 16 },
      { city: "將軍澳", demand: 60, supply: 22 },
    ],
    play: {
      title: "西貢場景選鞋 / 週末租借",
      whyHidden: "超本地、超低競爭，適合驗證『GEO + 地理需求』係咪成立。",
      suggestedMove:
        "內容先講岩石同溪澗，再試週末租鞋。量細，但可做成可複製嘅地區玩法。",
      effort: "medium",
      timeToSignal: "4–8 週",
    },
  },
  {
    id: "nb-2002r-protection-size",
    query: "new balance 2002r protection pack sizing",
    queryZh: "NB 2002R Protection Pack 尺碼",
    brand: "New Balance",
    model: "2002R Protection Pack",
    category: "lifestyle",
    region: "HK",
    intent: "size",
    playType: "resale",
    monthlyVolume: 1700,
    volumeTrendPct: 13,
    trendSeries: [48, 49, 50, 51, 52, 53, 54, 56, 57, 59, 60, 62],
    keywordDifficulty: 25,
    serpSaturation: 33,
    topResults: [
      { title: "2002R PP", domain: "newbalance.com", type: "brand" },
      { title: "Sizing thread", domain: "reddit.com", type: "forum" },
      { title: "Carousell", domain: "carousell.com.hk", type: "marketplace" },
    ],
    relatedQueries: [
      "2002r 偏細",
      "protection pack 灰",
      "2002r vs 1906r 尺碼",
    ],
    chatgptMentioned: true,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 4,
    aiShareOfVoice: 18,
    unansweredAngle: "尺碼討論散落 Reddit；香港轉售者需要『對 1906R 點揀』一句話答案。",
    cities: [
      { city: "旺角", demand: 79, supply: 48 },
      { city: "銅鑼灣", demand: 68, supply: 44 },
      { city: "荃灣", demand: 50, supply: 20 },
    ],
    play: {
      title: "尺碼轉換器 + 二手定價",
      whyHidden: "意圖接近成交，內容卻唔幫人下單。",
      suggestedMove:
        "用 2002R / 1906R / Kayano 互轉，連本地放售。減少退貨同爭議。",
      effort: "low",
      timeToSignal: "2–4 週",
    },
  },
  {
    id: "consignment-mongkok-fee",
    query: "sneaker consignment mong kok commission",
    queryZh: "波鞋寄賣 旺角 抽成",
    brand: "Service",
    model: "寄賣",
    category: "service",
    region: "HK",
    intent: "service",
    playType: "service",
    monthlyVolume: 860,
    volumeTrendPct: 18,
    trendSeries: [30, 31, 32, 33, 35, 36, 38, 40, 42, 44, 46, 49],
    keywordDifficulty: 10,
    serpSaturation: 15,
    topResults: [
      { title: "寄賣店 IG", domain: "instagram.com", type: "ugc" },
      { title: "Carousell fees", domain: "carousell.com.hk", type: "marketplace" },
      { title: "寄賣是什麼", domain: "blog.pixnet.net", type: "media" },
    ],
    relatedQueries: [
      "波鞋寄賣 抽成 比較",
      "旺角 波鞋店 收購",
      "二手波 點賣 香港",
    ],
    chatgptMentioned: false,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 0,
    aiShareOfVoice: 3,
    unansweredAngle: "人想比較抽成同安全，但資訊全喺 IG bio，AI 同 Google 都抓唔到。",
    cities: [
      { city: "旺角", demand: 88, supply: 41 },
      { city: "深水埗", demand: 62, supply: 27 },
      { city: "銅鑼灣", demand: 55, supply: 22 },
    ],
    play: {
      title: "透明抽成比較層",
      whyHidden: "資訊不透明本身就係機會：先做比較頁，再做自己嘅寄賣條款。",
      suggestedMove:
        "公開 8–10 間店抽成、結算日、真假責任。之後用最信任條款收貨。",
      effort: "medium",
      timeToSignal: "3–5 週",
    },
  },
  {
    id: "pegasus-41-overpronation-hk",
    query: "nike pegasus 41 overpronation",
    queryZh: "Pegasus 41 內八 香港",
    brand: "Nike",
    model: "Pegasus 41",
    category: "running",
    region: "HK",
    intent: "review",
    playType: "content",
    monthlyVolume: 1400,
    volumeTrendPct: 8,
    trendSeries: [40, 41, 42, 43, 44, 44, 45, 46, 47, 48, 48, 50],
    keywordDifficulty: 28,
    serpSaturation: 40,
    topResults: [
      { title: "Pegasus 41", domain: "nike.com", type: "brand" },
      { title: "Stability options", domain: "runnersworld.com", type: "media" },
      { title: "Gait analysis", domain: "reddit.com", type: "forum" },
    ],
    relatedQueries: [
      "內旋 跑鞋 香港",
      "kayano vs pegasus",
      "步態分析 香港",
    ],
    chatgptMentioned: true,
    perplexityCited: false,
    aiOverviewPresent: true,
    citationCount: 7,
    aiShareOfVoice: 28,
    unansweredAngle: "醫療化問題被全球媒體回答；香港步態分析服務無被連去產品。",
    cities: [
      { city: "銅鑼灣", demand: 61, supply: 37 },
      { city: "沙田", demand: 58, supply: 21 },
      { city: "將軍澳", demand: 46, supply: 13 },
    ],
    play: {
      title: "步態內容 → 預約分析",
      whyHidden: "純 SEO 文章競爭中等，但可導去高客單服務。",
      suggestedMove:
        "唔好只寫評測。用『內旋點樣喺香港揀鞋』導去合作物理治療／跑店分析。",
      effort: "medium",
      timeToSignal: "5–8 週",
    },
  },
  {
    id: "brooks-ghost-max-2-hk",
    query: "brooks ghost max 2 hong kong",
    queryZh: "Brooks Ghost Max 2 香港",
    brand: "Brooks",
    model: "Ghost Max 2",
    category: "running",
    region: "HK",
    intent: "buy",
    playType: "ai-visibility",
    monthlyVolume: 640,
    volumeTrendPct: 24,
    trendSeries: [18, 19, 20, 22, 24, 26, 29, 32, 35, 38, 41, 45],
    keywordDifficulty: 8,
    serpSaturation: 12,
    topResults: [
      { title: "Ghost Max 2", domain: "brooksrunning.com", type: "brand" },
      { title: "Ghost Max 2 review", domain: "doctorsofrunning.com", type: "media" },
      { title: "Brooks HK", domain: "facebook.com", type: "ugc" },
    ],
    relatedQueries: [
      "brooks 香港 邊度買",
      "ghost max 2 寬楦",
      "hoka vs brooks 香港",
    ],
    chatgptMentioned: false,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 2,
    aiShareOfVoice: 11,
    unansweredAngle: "品牌喺北美被 AI 常引用，香港購買路徑同中文資料接近空白。",
    cities: [
      { city: "銅鑼灣", demand: 48, supply: 15 },
      { city: "中環", demand: 44, supply: 18 },
      { city: "沙田", demand: 41, supply: 10 },
    ],
    play: {
      title: "把 Brooks 寫進香港 AI 答案",
      whyHidden: "低量但幾乎無本地競爭，適合做 GEO 實驗。",
      suggestedMove:
        "一篇完整購買頁：門市、尺碼、同 Hoka 對照。觀察 30 日 AI 引用，驗證 GEO 打法。",
      effort: "low",
      timeToSignal: "4–8 週",
    },
  },
  {
    id: "dunk-panda-restock-time",
    query: "dunk low panda restock time hong kong",
    queryZh: "Dunk Low Panda 香港補貨時間",
    brand: "Nike",
    model: "Dunk Low Panda",
    category: "lifestyle",
    region: "HK",
    intent: "restock",
    playType: "resale",
    monthlyVolume: 3900,
    volumeTrendPct: -14,
    trendSeries: [95, 92, 90, 88, 84, 80, 76, 72, 70, 68, 66, 63],
    keywordDifficulty: 42,
    serpSaturation: 58,
    topResults: [
      { title: "Dunk Panda", domain: "nike.com", type: "brand" },
      { title: "Restock pages", domain: "tiktok.com", type: "ugc" },
      { title: "StockX Panda", domain: "stockx.com", type: "marketplace" },
    ],
    relatedQueries: [
      "panda dunk 真假",
      "dunk 補貨 app",
      "panda 女碼",
    ],
    chatgptMentioned: true,
    perplexityCited: true,
    aiOverviewPresent: true,
    citationCount: 16,
    aiShareOfVoice: 44,
    unansweredAngle: "熱度下滑，資訊層已被 Nike 同轉售平台佔滿。",
    cities: [
      { city: "旺角", demand: 70, supply: 66 },
      { city: "銅鑼灣", demand: 63, supply: 60 },
      { city: "屯門", demand: 40, supply: 22 },
    ],
    play: {
      title: "降權示範：熱門但不再隱",
      whyHidden: "MVP 需要負例。高搜尋唔等於機會；供應同 AI 覆蓋都已經密。",
      suggestedMove: "唔建議新進場。如果已有貨盤，只做女碼／小碼尾貨，唔好再做內容。",
      effort: "high",
      timeToSignal: "弱",
    },
  },
  {
    id: "air-max-95-neon-retro",
    query: "air max 95 neon retro release",
    queryZh: "Air Max 95 Neon 復刻",
    brand: "Nike",
    model: "Air Max 95 Neon",
    category: "lifestyle",
    region: "SG",
    intent: "restock",
    playType: "resale",
    monthlyVolume: 2600,
    volumeTrendPct: 36,
    trendSeries: [22, 21, 23, 26, 30, 34, 40, 48, 57, 64, 72, 84],
    keywordDifficulty: 31,
    serpSaturation: 44,
    topResults: [
      { title: "SNKRS rumor", domain: "sneakernews.com", type: "media" },
      { title: "AM95 Neon", domain: "nike.com", type: "brand" },
      { title: "Carousell SG", domain: "carousell.sg", type: "marketplace" },
    ],
    relatedQueries: [
      "air max 95 新加坡",
      "neon 95 尺碼",
      "am95 抽籤",
    ],
    chatgptMentioned: true,
    perplexityCited: false,
    aiOverviewPresent: true,
    citationCount: 8,
    aiShareOfVoice: 30,
    unansweredAngle: "發售謠言已被媒體覆蓋；新加坡尺碼需求同中古溢價仍散亂。",
    cities: [
      { city: "Orchard", demand: 82, supply: 50 },
      { city: "Tampines", demand: 54, supply: 21 },
      { city: "Jurong", demand: 47, supply: 16 },
    ],
    play: {
      title: "復刻週期嘅預售情報（SG）",
      whyHidden: "升勢來自傳聞，窗口短。適合已有轉售能力嘅人，唔適合純內容站。",
      suggestedMove:
        "做尺碼需求登記，發售當日只做成交撮合。內容只服務名單，唔好博長尾 SEO。",
      effort: "medium",
      timeToSignal: "窗口 2–6 週",
    },
  },
  {
    id: "arcteryx-norvan-ld-hk",
    query: "arcteryx norvan ld hong kong",
    queryZh: "Arc'teryx Norvan LD 香港",
    brand: "Arc'teryx",
    model: "Norvan LD",
    category: "trail",
    region: "HK",
    intent: "buy",
    playType: "local-retail",
    monthlyVolume: 540,
    volumeTrendPct: 16,
    trendSeries: [20, 21, 22, 23, 24, 25, 27, 28, 30, 31, 33, 35],
    keywordDifficulty: 13,
    serpSaturation: 17,
    topResults: [
      { title: "Norvan LD", domain: "arcteryx.com", type: "brand" },
      { title: "Arc HK", domain: "arcteryx.com", type: "shop" },
      { title: "越野討論", domain: "uwants.com", type: "forum" },
    ],
    relatedQueries: [
      "始祖鳥 跑鞋 香港",
      "norvan 折扣",
      "越野 長距離 鞋",
    ],
    chatgptMentioned: false,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 1,
    aiShareOfVoice: 8,
    unansweredAngle: "高客單被品牌站壟斷，第三者中文評測同折扣情報幾乎冇。",
    cities: [
      { city: "中環", demand: 59, supply: 40 },
      { city: "銅鑼灣", demand: 51, supply: 33 },
      { city: "荃灣", demand: 38, supply: 10 },
    ],
    play: {
      title: "高客單越野鞋嘅第三方情報",
      whyHidden: "量低、客單高、品牌頁不能回答『值唔值得喺香港買』。",
      suggestedMove:
        "對照 Salomon / Hoka 長距離，跟 Outlet 同維修政策。適合已經做戶外內容嘅人。",
      effort: "low",
      timeToSignal: "4–7 週",
    },
  },
  {
    id: "sneaker-auth-service-hk",
    query: "sneaker authentication service hong kong",
    queryZh: "波鞋鑑定服務 香港",
    brand: "Service",
    model: "鑑定",
    category: "service",
    region: "HK",
    intent: "service",
    playType: "service",
    monthlyVolume: 1250,
    volumeTrendPct: 27,
    trendSeries: [26, 27, 29, 31, 34, 37, 41, 45, 50, 54, 59, 64],
    keywordDifficulty: 17,
    serpSaturation: 23,
    topResults: [
      { title: "StockX auth", domain: "stockx.com", type: "marketplace" },
      { title: "eBay authenticity", domain: "ebay.com", type: "marketplace" },
      { title: "鑑定師 IG", domain: "instagram.com", type: "ugc" },
    ],
    relatedQueries: [
      "現場鑑定 旺角",
      "鑑定 證書 香港",
      "carousell 鑑定",
    ],
    chatgptMentioned: false,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 2,
    aiShareOfVoice: 10,
    unansweredAngle: "人唔信任平台鑑定週期；想要本地、即日、可對質嘅服務，但網頁層空白。",
    cities: [
      { city: "旺角", demand: 90, supply: 32 },
      { city: "尖沙咀", demand: 74, supply: 21 },
      { city: "觀塘", demand: 53, supply: 14 },
    ],
    play: {
      title: "本地鑑定 API（對 Carousell 交易）",
      whyHidden: "搜尋同社交需求一齊升，SEO 仲停留喺海外平台品牌詞。",
      suggestedMove:
        "落地頁 + WhatsApp 預約，出公開鑑定報告格式。之後先考慮收費 SaaS。MVP 只驗證需求。",
      effort: "high",
      timeToSignal: "4–8 週",
    },
  },
  {
    id: "asics-gel-1130-vintage-hk",
    query: "asics gel 1130 vintage hong kong",
    queryZh: "Asics Gel-1130 古著 香港",
    brand: "Asics",
    model: "Gel-1130",
    category: "lifestyle",
    region: "HK",
    intent: "resale",
    playType: "resale",
    monthlyVolume: 1800,
    volumeTrendPct: 15,
    trendSeries: [34, 36, 37, 39, 41, 44, 46, 49, 51, 53, 55, 58],
    keywordDifficulty: 22,
    serpSaturation: 30,
    topResults: [
      { title: "GEL-1130", domain: "asics.com", type: "brand" },
      { title: "Vintage Asics", domain: "grailed.com", type: "marketplace" },
      { title: "古著波 香港", domain: "instagram.com", type: "ugc" },
    ],
    relatedQueries: [
      "1130 vs kayano 14",
      "gel 1130 尺碼",
      "古著 asics 真假",
    ],
    chatgptMentioned: false,
    perplexityCited: false,
    aiOverviewPresent: false,
    citationCount: 1,
    aiShareOfVoice: 9,
    unansweredAngle: "古著溢價資訊喺 IG，搜尋者同 AI 都找不到可靠年份／真假準則。",
    cities: [
      { city: "深水埗", demand: 72, supply: 34 },
      { city: "旺角", demand: 76, supply: 40 },
      { city: "中環", demand: 58, supply: 29 },
    ],
    play: {
      title: "1130 年份圖鑑 + 古著選貨",
      whyHidden: "中等需求、內容可護城（圖鑑難複製），適合有貨源嘅古著店。",
      suggestedMove:
        "用實物照片建立年份特徵頁，GEO 上會成為鑑定類問題嘅引用源。",
      effort: "medium",
      timeToSignal: "5–9 週",
    },
  },
];

export const opportunities: Opportunity[] = RAW.map((item) => ({
  ...item,
  scores: scoreOpportunity(item),
}));

export function getOpportunity(id: string) {
  return opportunities.find((item) => item.id === id);
}

export function getRelated(id: string, limit = 3) {
  const current = getOpportunity(id);
  if (!current) return [];
  return opportunities
    .filter((item) => item.id !== id)
    .sort((a, b) => {
      const aScore =
        (a.playType === current.playType ? 2 : 0) +
        (a.brand === current.brand ? 2 : 0) +
        (a.region === current.region ? 1 : 0) +
        (a.category === current.category ? 1 : 0);
      const bScore =
        (b.playType === current.playType ? 2 : 0) +
        (b.brand === current.brand ? 2 : 0) +
        (b.region === current.region ? 1 : 0) +
        (b.category === current.category ? 1 : 0);
      return bScore - aScore || b.scores.hidden - a.scores.hidden;
    })
    .slice(0, limit);
}

export function uniqueBrands() {
  return [...new Set(opportunities.map((item) => item.brand))].sort();
}

export function radarStats() {
  const hidden = opportunities.filter((item) => item.scores.hidden >= 80).length;
  const rising = opportunities.filter((item) => item.volumeTrendPct >= 20).length;
  const geoOpen = opportunities.filter((item) => item.scores.geoGap >= 70).length;
  const avg =
    opportunities.reduce((sum, item) => sum + item.scores.hidden, 0) /
    opportunities.length;
  return {
    total: opportunities.length,
    hidden,
    rising,
    geoOpen,
    avgHidden: Math.round(avg),
  };
}

export function sortOpportunities(list: Opportunity[], sort: SortKey) {
  const copy = [...list];
  switch (sort) {
    case "demand":
      return copy.sort((a, b) => b.monthlyVolume - a.monthlyVolume);
    case "geoGap":
      return copy.sort((a, b) => b.scores.geoGap - a.scores.geoGap);
    case "rising":
      return copy.sort((a, b) => b.volumeTrendPct - a.volumeTrendPct);
    default:
      return copy.sort((a, b) => b.scores.hidden - a.scores.hidden);
  }
}

export function searchOpportunities(list: Opportunity[], query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return list;
  return list.filter((item) => {
    const hay = [
      item.query,
      item.queryZh,
      item.brand,
      item.model,
      item.play.title,
      ...item.relatedQueries,
    ]
      .join(" ")
      .toLowerCase();
    return hay.includes(q);
  });
}
